export const APCA_LIVE_BASE_URL = "api.alpaca.markets"
export const APCA_PAPER_BASE_URL = "paper-api.alpaca.markets"
export const APCA_DATA_URL_STOCK = "https://data.alpaca.markets/v2"
export const APCA_DATA_URL_CRYPTO = "https://data.alpaca.markets/v1beta1/crypto"
export const APCA_STREAM_URL_STOCK = "wss://stream.data.alpaca.markets/v2/iex"
export const APCA_STREAM_URL_CRYPTO = "wss://stream.data.alpaca.markets/v1beta1/crypto"
